-- =========================================================
-- Supabase Database Schema for WhatsApp Message Monitor
-- Copy and paste this into Supabase SQL Editor -> Run
-- =========================================================

-- 1. Messages Table
CREATE TABLE IF NOT EXISTS messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  message_id TEXT UNIQUE NOT NULL,
  chat_jid TEXT NOT NULL,
  sender_jid TEXT NOT NULL,
  sender_name TEXT,
  chat_name TEXT,
  content TEXT,
  message_type TEXT DEFAULT 'text',
  is_from_me BOOLEAN DEFAULT FALSE,
  timestamp BIGINT NOT NULL,
  raw_json JSONB,
  ai_transcript TEXT,
  ai_translation TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Contacts Table
CREATE TABLE IF NOT EXISTS contacts (
  jid TEXT PRIMARY KEY,
  name TEXT,
  notify TEXT,
  phone TEXT,
  updated_at BIGINT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Chats Table
CREATE TABLE IF NOT EXISTS chats (
  jid TEXT PRIMARY KEY,
  name TEXT,
  unread_count INT DEFAULT 0,
  conversation_timestamp BIGINT,
  updated_at BIGINT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Keywords Table
CREATE TABLE IF NOT EXISTS keywords (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  keyword TEXT NOT NULL,
  type TEXT DEFAULT 'include',
  created_at BIGINT NOT NULL
);

-- 5. Indexes for Fast Searching
CREATE INDEX IF NOT EXISTS idx_messages_timestamp ON messages(timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_messages_chat_jid ON messages(chat_jid);
CREATE INDEX IF NOT EXISTS idx_messages_sender_jid ON messages(sender_jid);
CREATE INDEX IF NOT EXISTS idx_messages_message_type ON messages(message_type);

-- 6. Disable Row Level Security (RLS) for server API access or allow service role
ALTER TABLE messages DISABLE ROW LEVEL SECURITY;
ALTER TABLE contacts DISABLE ROW LEVEL SECURITY;
ALTER TABLE chats DISABLE ROW LEVEL SECURITY;
ALTER TABLE keywords DISABLE ROW LEVEL SECURITY;
