-- =========================================================
-- Supabase PostgreSQL Schema for Go-Notch Trip Monitor
-- Copy and paste this into Supabase SQL Editor -> Run
-- =========================================================

-- 1. Users Table (Stores user name, mobile, gender & 4-digit passcode)
CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  phone TEXT UNIQUE NOT NULL,
  name TEXT,
  gender TEXT DEFAULT 'Male',
  passcode TEXT,
  created_at BIGINT NOT NULL,
  updated_at BIGINT NOT NULL
);

-- 2. Subscriptions Table (Stores ₹2/mo or trial validity & plan dates)
CREATE TABLE IF NOT EXISTS subscriptions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_phone TEXT NOT NULL,
  plan_name TEXT DEFAULT 'Monthly Pro',
  plan_price INT DEFAULT 2,
  status TEXT DEFAULT 'active',
  started_at BIGINT NOT NULL,
  expires_at BIGINT NOT NULL,
  payment_id TEXT,
  order_id TEXT,
  created_at BIGINT NOT NULL,
  updated_at BIGINT NOT NULL
);

-- 3. Payments Table (Stores Razorpay order, payment ID & verification signatures)
CREATE TABLE IF NOT EXISTS payments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_phone TEXT NOT NULL,
  order_id TEXT UNIQUE NOT NULL,
  payment_id TEXT,
  signature TEXT,
  amount INT NOT NULL,
  currency TEXT DEFAULT 'INR',
  status TEXT DEFAULT 'created',
  method TEXT DEFAULT 'razorpay',
  created_at BIGINT NOT NULL,
  updated_at BIGINT NOT NULL
);

-- 4. Keywords Table (Stores Include / Exclude monitoring keywords per user)
CREATE TABLE IF NOT EXISTS keywords (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  keyword TEXT NOT NULL,
  type TEXT DEFAULT 'include',
  user_phone TEXT DEFAULT '',
  created_at BIGINT NOT NULL
);

-- Ensure user_phone column exists if keywords table was created earlier
DO $$ 
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_name = 'keywords' AND column_name = 'user_phone'
  ) THEN
    ALTER TABLE keywords ADD COLUMN user_phone TEXT DEFAULT '';
  END IF;
END $$;

-- 5. WhatsApp Connected Sessions Table (Tracks persistent connected WhatsApp per user)
CREATE TABLE IF NOT EXISTS whatsapp_sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_phone TEXT UNIQUE NOT NULL,
  connected_jid TEXT,
  connected_name TEXT,
  connected_phone TEXT,
  status TEXT DEFAULT 'connected',
  last_active BIGINT NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. Messages Table (Real-time WhatsApp messages)
CREATE TABLE IF NOT EXISTS messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  message_id TEXT UNIQUE NOT NULL,
  chat_jid TEXT NOT NULL,
  sender_jid TEXT NOT NULL,
  sender_name TEXT,
  chat_name TEXT,
  content TEXT,
  message_type TEXT DEFAULT 'text',
  is_from_me BOOLEAN DEFAULT FALSE,
  timestamp BIGINT NOT NULL,
  raw_json JSONB,
  ai_transcript TEXT,
  ai_translation TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. Contacts Table
CREATE TABLE IF NOT EXISTS contacts (
  jid TEXT PRIMARY KEY,
  name TEXT,
  notify TEXT,
  phone TEXT,
  updated_at BIGINT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 8. Chats Table
CREATE TABLE IF NOT EXISTS chats (
  jid TEXT PRIMARY KEY,
  name TEXT,
  unread_count INT DEFAULT 0,
  conversation_timestamp BIGINT,
  updated_at BIGINT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 9. Indexes for High Performance
CREATE INDEX IF NOT EXISTS idx_users_phone ON users(phone);
CREATE INDEX IF NOT EXISTS idx_subscriptions_user_phone ON subscriptions(user_phone);
CREATE INDEX IF NOT EXISTS idx_subscriptions_expires_at ON subscriptions(expires_at DESC);
CREATE INDEX IF NOT EXISTS idx_payments_user_phone ON payments(user_phone);
CREATE INDEX IF NOT EXISTS idx_keywords_user_phone ON keywords(user_phone);
CREATE INDEX IF NOT EXISTS idx_messages_timestamp ON messages(timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_messages_chat_jid ON messages(chat_jid);

-- 10. Disable Row Level Security (RLS) for Backend API Access
ALTER TABLE users DISABLE ROW LEVEL SECURITY;
ALTER TABLE subscriptions DISABLE ROW LEVEL SECURITY;
ALTER TABLE payments DISABLE ROW LEVEL SECURITY;
ALTER TABLE keywords DISABLE ROW LEVEL SECURITY;
ALTER TABLE whatsapp_sessions DISABLE ROW LEVEL SECURITY;
ALTER TABLE messages DISABLE ROW LEVEL SECURITY;
ALTER TABLE contacts DISABLE ROW LEVEL SECURITY;
ALTER TABLE chats DISABLE ROW LEVEL SECURITY;
